matrix:
  include:
    - language: java
      jdk:
        - openjdk12
      services:
        - docker
      before_install:
        - chmod +x mvnw
      install: true
      script:
        - ./mvnw clean spring-boot:build-image -DskipTests=true
      cache:
        directories:
          - $HOME/.m2
          - docker_images
