apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: charity
build:
  artifacts:
  - image: ashraf1abdelrasool/charity
    context: .
    jib:
      project: org.revo:charity
deploy:
  kubectl:
    manifests:
    - k8s/workloads/charity-config.yaml
    - k8s/workloads/charity-dep.yaml
    - k8s/workloads/charity-svc.yaml
