spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
    show-sql: true
    open-in-view: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: ['*']
springdoc:
  swagger-ui:
    path: /swagger-ui.html
