spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: ['*']
springdoc:
  swagger-ui:
    path: /swagger-ui.html
