spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://salt.db.elephantsql.com:5432/fskhvmnd
    username: fskhvmnd
    password: ObYt3_pRnWMdFHigiFrflDn15elwjFmc
    initialization-mode: always
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: ['*']
springdoc:
  swagger-ui:
    path: /swagger-ui.html
