spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:h2:file:./db;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: ['*']
springdoc:
  swagger-ui:
    path: /swagger-ui.html
