package org.revo.charity.controller.filter.vm;

public enum Condition {
    MATCH, NOT_MATCH, LIKE, NOT_LIKE, EQUAL, NOT_EQUAL, LESS_THAN, LESS_THAN_EQUAL, GREATER_THAN, GREATER_THAN_EQUAL, EQUAL_DATE, NOT_EQUAL_DATE, GREATER_THAN_DATE, GREATER_THAN_EQUAL_DATE, LESS_THAN_DATE, LESS_THAN_EQUAL_DATE, IN, NOT_IN, MEMBER, NOT_MEMBER, IS_NULL, WITHIN, BETWEEN
}
